---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 {{ inventory_hostname }}"

- name: Ensure K3s node service is disabled
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: stopped
    enabled: no

- name: Ensure K3s master service is enabled
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes

- name: Compress the OS image
  community.general.archive:
    path: /opt/os.img
    dest: "/opt/ubuntu-{{ inventory_hostname }}.img.xz"
    format: xz
  delegate_to: "{{ groups['vm'][0] }}"