---

ansible_port: "{{ image_ssh_port }}"
ansible_host: "{{ vm_ip }}"
ansible_user: "{{ cluster_user }}"
rpi_static_ip: "{{ master_static_ip }}"
k3s_master_service_status: yes
k3s_node_service_status: no
has_disk: true
